- name: Build and deploy to GitHub Pages
  # You may pin to the exact commit or the version.
  # uses: EdricChan03/action-build-deploy-ghpages@28ae857b6c5037451527ef9e3d50de8a96cc49fa
  uses: EdricChan03/action-build-deploy-ghpages@v3.1.0
  with:
    # The GitHub installation token.
    github_token: 
    # The token used for triggering a deploy request. (This is no longer needed - see https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/46519/highlight/true#M6551)
    gh_pages_token: # optional
    # The branch to deploy the Jekyll site to.
    gh_pages_branch: # optional, default is gh-pages
    # The folder to build the Jekyll site to.
    gh_pages_dist_folder: # optional, default is _site
    # The commit message to use when deploying the Jekyll site.
    gh_pages_commit_message: # optional
    # The repository to deploy the Jekyll site to.
    remote_repo: # optional
    # Options to pass to the Jekyll build command.
    jekyll_build_opts: # optional
    # The username to use for the committer of the commit.
    committer_username: # optional
    # The email to use for the committer of the commit.
    committer_email: # optional
    # Whether to use the --force flag on git push.
    git_force: # optional, default is true
    # Whether to override the gh-pages branch.
    override_gh_pages_branch: # optional, default is false
    # Whether to add the .nojekyll file to the deployed site.
    gh_pages_add_no_jekyll: # optional, default is true
    # Whether to skip deployment after a successful build.
    skip_deploy: # optional, default is false
    # Whether to show detailed logs from the bundle install command.
    show_bundle_log: # optional, default is false
    # A specific version of Bundler to be used.
    bundler_version: # optional
    # The Jekyll environment to use when building the site. (See https://jekyllrb.com/docs/configuration/environments/)
    jekyll_env: # optional, default is production
